stages:
    - build
    - deploy
build:
  stage: build
  image:
    name: mcr.microsoft.com/dotnet/sdk:6.0
  script:
    - | 
      dotnet publish \
      --configuration Release \
      --runtime linux-x64 \
      --self-contained \
      -p:PublishSingleFile=true \
      -p:PublishReadyToRun=true \
      -p:DebugType=embedded \
      --output publish_output
  artifacts:
    name: "ipfs-pin-util-linux_x64"
    paths:
      - publish_output/*
    expire_in: 1 week
    when: on_success
  rules:
    - if: '$CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH'
deploy:
  stage: deploy
  image:
    name: debian:11
  before_script:
    - apt update -y
    - apt install -y rsync openssh-client
    - eval $(ssh-agent -s)
    - chmod 400 "${SSH_PRIVATE_KEY}"
    - ssh-add "${SSH_PRIVATE_KEY}"
    - mkdir -p ~/.ssh
    - chmod 700 ~/.ssh
    - cp "${SSH_KNOWN_HOSTS}" ~/.ssh/known_hosts
    - chmod 644 ~/.ssh/known_hosts
  script:
    - rsync -rP publish_output/ debian@ipfs-01.owo.systems:ipfs-pin-util/